### ISSUE TITLE
出现了一个报错，不能生成mp3了，WSServerHandshakeError: 403。

### ISSUE THREAD

**Issue by jun-jing** [kuangdd2024/auto-video-generateor#7]
`Running on public URL: https://f8dbd510252fbd9f18.gradio.live
split_sentences: 100%|█████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 1005.35it/s]
split_sentences 输入: 关键点是武汉F天下的独栋别墅
split_sentences 输出: ['关键点是武汉F天下的独栋别墅']
synthesize_speech:   0%|                                                                         | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "D:\Program\anaconda3\envs\py310-venv_20241003_223441-XHS_onekey_generate_video_audio\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Program\anaconda3\envs\py310-venv_20241003_223441-XHS_onekey_generate_video_audio\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Program\anaconda3\envs\py310-venv_20241003_223441-XHS_onekey_generate_video_audio\Scripts\edge-tts.exe\__main__.py", line 7, in <module>
  File "D:\Program\anaconda3\envs\py310-venv_20241003_223441-XHS_onekey_generate_video_audio\lib\site-packages\edge_tts\util.py", line 136, in main
    asyncio.run(amain())
  File "D:\Program\anaconda3\envs\py310-venv_20241003_223441-XHS_onekey_generate_video_audio\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Program\anaconda3\envs\py310-venv_20241003_223441-XHS_onekey_generate_video_audio\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\Program\anaconda3\envs\py310-venv_20241003_223441-XHS_onekey_generate_video_audio\lib\site-packages\edge_tts\util.py", line 131, in amain
    await _run_tts(args)
  File "D:\Program\anaconda3\envs\py310-venv_20241003_223441-XHS_onekey_generate_video_audio\lib\site-packages\edge_tts\util.py", line 65, in _run_tts
    async for chunk in tts.stream():
  File "D:\Program\anaconda3\envs\py310-venv_20241003_223441-XHS_onekey_generate_video_audio\lib\site-packages\edge_tts\communicate.py", line 506, in stream
    async for message in self.__stream():
  File "D:\Program\anaconda3\envs\py310-venv_20241003_223441-XHS_onekey_generate_video_audio\lib\site-packages\edge_tts\communicate.py", line 365, in __stream
    async with aiohttp.ClientSession(
  File "D:\Program\anaconda3\envs\py310-venv_20241003_223441-XHS_onekey_generate_video_audio\lib\site-packages\aiohttp\client.py", line 1355, in __aenter__
    self._resp: _RetType = await self._coro
  File "D:\Program\anaconda3\envs\py310-venv_20241003_223441-XHS_onekey_generate_video_audio\lib\site-packages\aiohttp\client.py", line 949, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url='wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&ConnectionId=5d5d79d4323d4caa8f17906682c83cbb'`

**Comment by kuangdd2024** [comment]
国内被禁了，用vpn则可以。

国内被禁：
https://github.com/rany2/edge-tts/issues/286

用vpn成功：
https://www.bilibili.com/video/BV1d2SkYLEHb/?vd_source=11be452e642f9850d7f3b3275418907c
